[13:16] Mohammad Zafar

name: Terraform Azure

 

on:

  push:

    branches:

      - main

 

jobs:

  build:

    runs-on: ubuntu-latest

 

    steps:

    - name: Checkout code

      uses: actions/checkout@v2

 

    - name: Set up Terraform

      uses: hashicorp/setup-terraform@v1

      with:

        terraform_version: 1.0.0

 

    - name: Login to Azure

      uses: azure/login@v1

      with:

        creds: ${{ secrets.AZURE_CREDENTIALS }}

 

    - name: Initialize Terraform

      run: terraform init

 

    - name: Plan Terraform

      run: terraform plan -out=tfplan

 

    - name: Apply Terraform

      run: terraform apply -auto-approve tfplan

 

    - name: Clean up Terraform files

      run: rm -rf .terraform

 

    - name: Logout from Azure

      uses: azure/logout@v1


[13:32] Mohammad Zafar

name: Terraform Azure

 

on:

  push:

    branches:

      - main

 

jobs:

  build:

    runs-on: ubuntu-latest

 

    steps:

    - name: Checkout code

      uses: actions/checkout@v2

 

    - name: Install Azure CLI

      run: |

        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

 

    - name: Set up Terraform

      uses: hashicorp/setup-terraform@v1

      with:

        terraform_version: 1.0.0

 

    - name: Login to Azure

      uses: azure/login@v1

      with:

        creds: ${{ secrets.AZURE_CREDENTIALS }}

 

    - name: Initialize Terraform

      run: terraform init

 

    - name: Plan Terraform

      run: terraform plan -out=tfplan

 

    - name: Apply Terraform

      run: terraform apply -auto-approve tfplan

 

    - name: Clean up Terraform files

      run: rm -rf .terraform

